In [ ]:
# 约定俗称这样引入,这样命名
# 矩阵运算里常用
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
# 这个意思是创建一个二维数组（矩阵），其中包含两行三列的元素。第一行是 [1, 2, 3]，第二行是 [4, 5, 6]。
# 疑问: 为什么要np包一层,而不能直接用二维数组呢
# 因为 NumPy 提供了许多用于数组和矩阵操作的高效函数和方法，这些功能在处理大型数据集时非常有用。直接使用 Python 的内置列表来表示二维数组虽然可以实现基本的功能，但在性能和功能上都不如 NumPy 数组。例如，NumPy 数组支持向量化操作，可以一次性对整个数组进行计算，而不需要使用循环，这大大提高了计算效率。此外，NumPy 还提供了丰富的线性代数、统计和数学函数，使得矩阵运算更加方便和高效。因此，使用 NumPy 来处理二维数组是更好的选择。
print(array)
print(type(array))  # <class 'numpy.ndarray'> 就是被numpy包了一层

print("number of dimensions:", array.ndim)  # 输出数组的维度
# 维度可以理解为轴数，对于二维数组来说，维度是2，表示有两条轴：行轴和列轴
print("shape of array:", array.shape)  # 输出数组的形状 (行数, 列数)
print("size of array:", array.size)  # 输出数组的元素总数

# 三维数组怎么创建
# 就想象成二维数组是一张纸,然后不断叠放二维数组,就成了三维的了
# 每个数字不过是拥有了x,y,z三个位置 (以此类推到更高维度就是x,y,z,...的位置)
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
array_3d = np.array([[[1, 2, 3], [4, 5, 6]]])  # 这个也是三维的
print("3D array:\n", array_3d)
print("number of dimensions:", array_3d.ndim)  # 输出三维数组的维度
print("shape of 3D array:", array_3d.shape)  # 输出三维数组的形状 (深度, 行数, 列数)
# 这个shape是按从外到内一个一个[] 往外吐的

# 不常用的属性
print("data type of array elements:", array.dtype)  # 输出数组元素的数据类型
print("item size of array elements:", array.itemsize)  # 输出数组中每个元素的字节大小
print("total bytes of array:", array.nbytes)  # 输出数组占用的总字节数


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
number of dimensions: 2
shape of array: (2, 3)
size of array: 6
3D array:
 [[[1 2 3]
  [4 5 6]]]
number of dimensions: 3
shape of 3D array: (1, 2, 3)
data type of array elements: int64
item size of array elements: 8
total bytes of array: 48
