In [ ]:
import numpy as np

a = np.array([1, 2, 3])
a2 = [1, 2, 3]
print(a)  # 发现打印出来没有逗号分隔
print(type(a))  # <class 'numpy.ndarray'>
print(a2)
print(type(a2))  # <class 'list'>

[1 2 3]
<class 'numpy.ndarray'>
[1, 2, 3]
<class 'list'>


In [ ]:
import numpy as np

a = np.array([1, 2, 3], dtype=np.int64)
print(a.dtype)  # 输出数组元素的数据类型
# 其他还有这些常用类型
# np.int32, np.int64  疑问:np.int好像被废弃了?
# np.float, np.float32, np.float64
# np.bool

int64


In [10]:
import numpy as np

# 创建一个二维数组
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.shape)  # 输出数组的形状
# 创建一个三维矩阵
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a)
print(a.shape)  # 输出数组的形状

# 创建一个2x3的全零数组
a = np.zeros((2, 3))
print(a)
print(a.shape)  # 输出数组的形状
# 创建一个2x3的全一数组
a = np.ones((2, 3))
print(a)
print(a.shape)  # 输出数组的形状
# 创建一个2x3的全空数组
a1 = np.empty((2, 3))
print(a1)
print(a1.shape)  # 输出数组的形状
# 疑问为什么empty数组里面会有随机值，而不是全零或全一
# 答：np.empty() 创建的数组不会初始化数组元素的值，因此数组中可能包含随机的内存值。它比 np.zeros() 和 np.ones() 更高效，但需要注意数组中的初始值是未定义的。


[[1 2 3]
 [4 5 6]]
(2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)
[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)
[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [ ]:
import numpy as np

# 创建一个有序数组(下面的意思是从10开始到20结束，步长为2)
a = np.arange(10, 20, 2)  # 没设置shape默认是一维数组
print(a)
print(a.shape)  # 输出数组的形状
# 创建一个有序数组,自己定义shape(意思是先生成一个一维数组,数字从0到11，然后通过reshape改变其形状,3行4列)
a = np.arange(12).reshape((3, 4))  # 注意reshape里面还有个括号
print(a)
print(a.shape)  # 输出数组的形状

# 创建一个从0到10的等间隔数组，包含5个元素(0到10分5段)
a = np.linspace(0, 10, 5)
# a = np.linspace(0, 10, 5).reshape((2,3))  #如果reshape以后元素数量不匹配会报错
print(a)
print(a.shape)  # 输出数组的形状
# 疑问有些生成的数字是0.  1.带个点 这是什么?
# 答：带点的数字表示浮点数（float），而没有点的数字表示整数（int）。np.linspace 默认生成的是浮点数数组。

[10 12 14 16 18]
(5,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
[ 0.   2.5  5.   7.5 10. ]
(5,)
