In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.arange(4)
print(a, b)

# 矩阵运算
c = a - b
print(c)
# 另外还有哪些矩阵运算
# 可以用的运算符号有
# 加法: +
# 减法: -
# 乘法: *
# 除法: /
# 幂运算: **
# 取模: %

# 矩阵运算还可以使用numpy提供的函数
c = 10 * np.sin(a)
print(c)
# 其他常用的numpy函数还有：
# np.transpose() 转置矩阵
# np.linalg.inv() 求逆矩阵
# np.linalg.det() 求行列式
# np.sqrt() 开平方
# np.exp() 指数运算
# np.log() 对数运算
# np.sin() 正弦函数
# np.cos() 余弦函数
# np.tan() 正切函数
# np.arcsin() 反正弦函数
# np.arccos() 反余弦函数
# np.arctan() 反正切函数


[1 2 3 4] [0 1 2 3]
[1 1 1 1]
[ 8.41470985  9.09297427  1.41120008 -7.56802495]
10
10


In [ ]:
# 用list可以这样实现类似效果(仅限一维array)
a = [1, 2, 3, 4]
b = [0, 1, 2, 3]
c = [a_i - b_i for a_i, b_i in zip(a, b)]
print(c)

[1, 1, 1, 1]


In [ ]:
a = [1, 2, 3, 4]
b = [0, 1, 2, 3]
c = a - b
# 不能直接对列表进行减法运算,元组
print(c)

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.arange(4)

print(b)
print(b < 3)  # 返回一个布尔array，表示b中每个元素是否小于3
print(b[b < 3])  # 使用布尔索引，返回b中小于3的元素
# 这个的意思是，先生成一个布尔array，表示b中每个元素是否小于3，然后用这个布尔array对b进行索引(t的返回,f的不返回)

[0 1 2 3]
[ True  True  True False]
[0 1 2]


In [ ]:
import numpy as np

# a = np.array([1, 1], [0, 1]) 注意这句是错的,少个[]
a = np.array([[1, 1], [0, 1]])
b = np.arange(4).reshape(2, 2)
print(a)
print(b)

# 矩阵运算还可以使用numpy提供的函数
c = a * b
print(c)
c = np.dot(a, b)  # 矩阵乘法(和上面做区分)
print(c)
c = a.dot(b)  # 两种写法是一样
print(c)
# np.sum() 求和(就是矩阵里的元素的和)
# np.min() 最小值
# np.max() 最大值
# np.argmin() 最小值索引
# np.argmax() 最大值索引
# np.mean() 平均值
# np.median() 中位数
# np.std() 标准差
# np.var() 方差
# np.round() 四舍五入
# np.ceil() 向上取整
# np.floor() 向下取整
# np.abs() 取绝对值
# np.sign() 取符号

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))
# print(np.min(a))
# print(np.max(a))
# ...其他这些函数也可以加上axis

# axis代表维度, axis=0表示按列求和，axis=1表示按行求和
# 比较容易搞错,0是沿着行方向对列进行操作,1是沿着列方向对行进行操作
# 莫凡说0是按行求和,实际是这个意思.   但是还是说按列求和好
# 列是维度0,行是维度1  (按照从外往内理解 [[1, 1], [0, 1]])
# 那如果是3维矩阵呢，axis=0表示按第0维求和，axis=1表示按第1维求和，axis=2表示按第2维求和
# 所以0就是z轴,1就是y轴,2就是x轴
d = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]  # 三维矩阵,shape是(2, 2, 2)
print(np.sum(d, axis=0))
print(np.sum(d, axis=1))
print(np.sum(d, axis=2))

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]
3
[1 2]
[2 1]
[[ 6  8]
 [10 12]]
[[ 4  6]
 [12 14]]
[[ 3  7]
 [11 15]]
[[[1 3]
  [2 4]]]


In [ ]:
import numpy as np

# 意思是生成一个2x2的随机矩阵，矩阵中的元素在[0, 1)范围内(这个是random默认的)
# np.random.random((2, 2)) 和 np.random.rand(2, 2) 都可以生成一个2x2的随机矩阵，矩阵中的元素在[0, 1)范围内。
a = np.random.random((2, 2))  # 注意这个有括号
print(a)
a = np.random.rand(2, 2)
print(a)

[[0.20761759 0.02335237]
 [0.04854661 0.89788939]]
