In [ ]:
import numpy as np

a = np.arange(2, 14).reshape(3, 4)
print(a)
print(np.argmin(a))  # 最小值的索引
print(np.argmax(a))  # 最大值的索引 (这个索引是看成一维输出的)
# (和上一节一样,也可以加上axis参数,不加就是全部元素一起考察)

print(np.mean(a))  # 平均值
print(np.mean(a, axis=0))
# 按列计算平均值 也是从最外层开始压扁,这个思路,压扁正好是考察列的mean
print(np.mean(a, axis=1))  # 按行计算平均值
print(np.median(a))  # 中位数 (这里正好平均数和中位数一样)
print(np.cumsum(a))  # 累加和 (元素0,元素0+元素1,元素0+元素1+元素2,...)
print(np.diff(a))  # 差分 (每个元素与前一个元素的差)
print(np.nonzero(a))  # 非零元素的索引 (返回的是一个元组,每个元素是对应维度的索引)
# 这里不能想成压扁了, 要从外往内看 元组第一个元素是维度1的索引(最外层开始看),第二个元素是维度0的索引

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
7.5
[6. 7. 8. 9.]
[ 3.5  7.5 11.5]
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


In [ ]:
a = np.array([[0, 1, 0], [2, 0, 3]])
np.nonzero(a)
# (array([0, 1, 1]), array([1, 0, 2]))

a = np.array([[[0, 1], [2, 0]], [[0, 0], [0, 3]]])
print(a.shape)  # (2, 2, 2)

np.nonzero(a)
# (array([0, 0, 1]), array([0, 1, 1]), array([1, 0, 1]))
# a[0][0][1] = 1
# a[0][1][0] = 2
# a[1][1][1] = 3  这样想就好了

In [ ]:
import numpy as np

# a = np.array([[4, 5, 3, 2], [9, 6, 7, 8], [13, 10, 11, 12]])
a = np.array([[9, 6, 7, 8], [4, 5, 3, 2], [13, 10, 11, 12]])

print(np.sort(a))  # 排序 (默认按每一行进行排序,可以加上axis参数指定维度)
d = [[[3, 1], [4, 2]]]
print(np.sort(d))
# 对三维矩阵进行排序 (默认沿最后一个轴（axis=-1）排序，也就是"最内层"那一维)
d = [[[7, 5], [8, 6]], [[3, 1], [4, 2]]]
print(np.sort(d))

print(np.transpose(a))  # 转置 (交换矩阵的行和列)
print(a.T)  # 转置的另一种写法 (等价于 np.transpose(a))
print((a.T).dot(a))  # 转置矩阵与原矩阵的点积  (以后可能经常用到的运算)

print(np.clip(a, 5, 10))
# 将数组中的元素限制在指定的范围内 (小于5的变为5,大于10的变为10)
# 在图像处理中比如, 可以将像素值限制在0到255之间

[[ 6  7  8  9]
 [ 2  3  4  5]
 [10 11 12 13]]
[[[1 3]
  [2 4]]]
[[[5 7]
  [6 8]]

 [[1 3]
  [2 4]]]
[[ 9  4 13]
 [ 6  5 10]
 [ 7  3 11]
 [ 8  2 12]]
[[ 9  4 13]
 [ 6  5 10]
 [ 7  3 11]
 [ 8  2 12]]
[[266 204 218 236]
 [204 161 167 178]
 [218 167 179 194]
 [236 178 194 212]]
[[ 9  6  7  8]
 [ 5  5  5  5]
 [10 10 10 10]]
