In [10]:
import numpy as np

a = np.arange(3, 15)
print(a)
print(a[2])

a = np.arange(3, 15).reshape(3, 4)
print(a)
print(a[2])  # 注意和上面的区别
print(a[0][2])
print(a[0, 2])  # 两种写法

# 可以用和list索引一样的操作
print(a[:, 1])  # 取所有行的1号列
print(a[2, :])  # 取所有列的2号行
print(a[0:2, 1:3])
# 类似于list的切片操作,这里取0,1行(2行不到),1,2列(3列不到) (注意索引是左闭右开)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
5
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
5
5
[ 4  8 12]
[11 12 13 14]
[[4 5]
 [8 9]]


In [ ]:
import numpy as np

a = np.arange(3, 15).reshape(3, 4)

# 迭代每一行 (可以用c语言二维数组的方式来理解,就把外层指针拿出来类似的)
for row in a:
    print(row)

# 迭代每一列 (常见的狡猾做法)
for col in a.T:
    print(col)

# 迭代每一项
# flat将矩阵展平为一维数组，便于迭代每一项
for item in a.flat:
    print(item)
print(a.flat)
print(a.flat[:])  # 这样就会下面一样了(是numpy里实现的操作,记住就好了)
print(a.flatten())
# flat和flatten的区别在于，flat产生一个迭代器(总之是个obj)，而flatten会返回一个新的array。

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
3
4
5
6
7
8
9
10
11
12
13
14
[ 3  4  5  6  7  8  9 10 11 12 13 14]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
