In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 纵向合并 (列方向合并)
c = np.vstack((a, b))  # vertical stack
print(c)
print(c.shape)

# 横向合并 (行方向合并)
d = np.hstack((a, b))  # horizontal stack
print(d)
print(d.shape)
# 注意输出的是(6,)不是(6,1) 即这是一维的根本不存在第二个维度,随意shape只有一个数字

# 说行列方向合并更准确, 想象a放好以后,拿着b往哪里放
# 纵向合并就是把b放在a的下面,就是列方向往下放;  横向合并就是把b放在a的右边

[[1 2 3]
 [4 5 6]]
(2, 3)
[1 2 3 4 5 6]
(6,)


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a.shape)
print(a.T)  # 没办法把一维数组转置成列向量
print(a.T.shape)  # shape没变

print(a[np.newaxis, :])  # 增加一个新的轴，使其变成二维数组
print(a[np.newaxis, :].shape)  # 查看新数组的形状
print(a[:, np.newaxis])  # 增加一个新的轴，使其变成列向量
print(a[:, np.newaxis].shape)  # 查看新数组的形状
# 因为[np.newaxis, :]这个写法 newaxis被放在了前面，shape会变成(1, 3),就是加上前面那个1
# 而[:, np.newaxis]这个写法 newaxis被放在了后面，shape会变成(3, 1),就是加上后面那个1
# 那shape变成了(3,1),就顺利变成列向量了

a = np.array([1, 2, 3])[:, np.newaxis]  # 可以定义的时候直接加在后面
b = np.array([4, 5, 6])[:, np.newaxis]  # 也把b变成列向量
# 纵向合并 (按行合并)
c = np.vstack((a, b))  # vertical stack
print(c)
print(c.shape)

# 横向合并 (按列合并)
d = np.hstack((a, b))  # horizontal stack
print(d)
print(d.shape)

print(np.hstack((a, b, b, a)))  # 可以多个合并

(3,)
[1 2 3]
(3,)
[[1 2 3]]
(1, 3)
[[1]
 [2]
 [3]]
(3, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)
[[1 4 4 1]
 [2 5 5 2]
 [3 6 6 3]]


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 使用concatenate进行合并 (可以同时实现vstack和hstack两个函数的功能)
e = np.concatenate((a, b, b, a), axis=0)
print(e)
print(e.shape)
# e = np.concatenate((a, b, b, a), axis=1)  # 报错,因为本身a,b没有第二个维度

a = np.array([1, 2, 3])[:, np.newaxis]
b = np.array([4, 5, 6])[:, np.newaxis]  # (3,1)
e = np.concatenate((a, b, b, a), axis=0)  # 列方向合并(维度0)
# e = np.concatenate((a, b, b, a))  # 默认是维度0
print(e)
print(e.shape)
e = np.concatenate((a, b, b, a), axis=1)  # 行方向合并(维度1)
print(e)
print(e.shape)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# 或者不用newaxis,直接reshape成(3,1)也行
f = np.concatenate((a.reshape(3, 1), b.reshape(3, 1)), axis=1)
print(f)
print(f.shape)

[1 2 3 4 5 6 4 5 6 1 2 3]
(12,)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [4]
 [5]
 [6]
 [1]
 [2]
 [3]]
(12, 1)
[[1 4 4 1]
 [2 5 5 2]
 [3 6 6 3]]
(3, 4)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)
