In [ ]:
import numpy as np

a = np.arange(12).reshape(3, 4)  # 生成一个3x4的数组
print(a)

# 水平分割 (行方向分割)
h_split = np.hsplit(a, 2)  # 将数组水平分割成2个子数组
# h_split = np.hsplit(a, 3)  # 整除不了报错
print(h_split)

# 垂直分割 (列方向分割)
v_split = np.vsplit(a, 3)  # 将数组垂直分割成3个子数组
print(v_split)
# 注意: 水平垂直分割都要求对应列行能被整除

a_split = np.split(a, 2, axis=1)  # 行方向分割成2个子数组, 同样要求整除
print(a_split)
a_split = np.array_split(a, 2, axis=1)  # 行方向分割成2个子数组, 可以不整除
print(a_split)
a_split = np.array_split(a, 3, axis=1)  # 可以要求不等量的分割
# 不等的分割,分割逻辑是尽量平均分配,4/3=1...1, 所以前两个子数组有2列, 最后一个子数组有1列
# 疑问:希望举更多例子来理解这个里面的逻辑
print(a_split)
# split和array_split的区别: split要求能整除, array_split可以不整除

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
