In [ ]:
import numpy as np

a = np.arange(4)
b = a
print(a)
print(b)

a[0] = 100
print(a)
print(b)
print(b is a)  # True, b和a指向同一个内存空间
# 发现直接赋值是浅拷贝, 修改a会影响b(内容在同一个内存空间)
b[2] = 200
print(a)
print(b)

c = a.copy()  # 使用copy方法进行深拷贝
print(c)

a[0] = 200
print(a)
print(c)
print(c is a)  # False, c和a指向不同的内存空间
# 发现使用copy方法进行深拷贝后, 修改a不会影响c(内容在不同的内存空间)

[0 1 2 3]
[0 1 2 3]
[100   1   2   3]
[100   1   2   3]
True
[100   1 200   3]
[100   1 200   3]
[100   1 200   3]
[200   1 200   3]
[100   1 200   3]
False
