In [19]:
import numpy as np
import pandas as pd

s = pd.Series([1, "yuan", 3.382, 4, "fan", np.nan])
# np.nan是一个特殊的浮点数，表示“不是一个数字”（Not a Number），通常用于表示缺失或无效的数据。
print(np.nan)  # 输出: nan
print(s)
# 发现输出的每个元素,有序号; 最后dtype就是每个元素的类型
# dtype为什么是obj? 因为Series中的元素类型不统一，包含了整数、浮点数、字符串和NaN，pandas会将其统一为对象类型（object）。
# 字符串一般会被提升为对象类型，而整数和浮点数可以被提升为浮点数，但由于存在字符串，整个Series的dtype最终被确定为对象类型。

s = pd.Series([1, 3.382, 4, np.nan])
print(s)
# 此时，Series中的元素类型统一为浮点数（float64），因为整数和浮点数可以被提升为浮点数，而NaN也是浮点数的一种表示方式。

nan
0        1
1     yuan
2    3.382
3        4
4      fan
5      NaN
dtype: object
0    1.000
1    3.382
2    4.000
3      NaN
dtype: float64


In [20]:
import numpy as np
import pandas as pd

dates = pd.date_range("20270101", periods=6)
# 意思是从2027年1月1日开始，生成一个包含6个连续日期的日期范围。
print(dates)
# 为什么没有序号了,freq又是什么? 因为pd.date_range生成的是一个DatetimeIndex对象，它是一个特殊的索引类型，用于表示时间序列数据。DatetimeIndex对象本身不包含序号，而是通过索引来访问日期。freq表示日期范围的频率，默认情况下，pd.date_range生成的日期范围是按天递增的，因此freq为'D'，表示每天。

df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
print(df)
print(df.values)
print(type(df.values))  # 输出DataFrame中数据的类型,是np.ndarray
print(df.index)
print(df.columns)
# 意思是创建一个6行4列的DataFrame，行索引index为之前生成的日期范围，列名columns为"A"、"B"、"C"和"D"。
# DataFrame中的数据是从标准正态分布(因为用了randn)中随机生成的浮点数。
# DataFrame里面的内容就把他看做是np里的二维矩阵就好了

# 以上输出的dtype是索引本身的类型
print(df.dtypes)  # 这是输出每一列的数据类型,即DataFrame的'内容物'类型
df = pd.DataFrame(np.arange(12).reshape(3, 4))
print(df)
# 看下默认的index和columns
print(df.index)
print(df.columns)
print(df.values)


DatetimeIndex(['2027-01-01', '2027-01-02', '2027-01-03', '2027-01-04',
               '2027-01-05', '2027-01-06'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2027-01-01  0.178939  0.714475 -2.989604 -0.124596
2027-01-02  0.087730 -0.471770  0.469317 -1.004326
2027-01-03  1.389915  0.036649  0.099591  0.346530
2027-01-04 -0.923515 -0.227732  1.226788 -0.948088
2027-01-05 -0.080731  0.973574  1.194009  1.462342
2027-01-06 -1.137954 -1.362732  0.229802 -0.690815
[[ 0.17893894  0.71447494 -2.98960392 -0.12459589]
 [ 0.08772962 -0.47177038  0.46931653 -1.0043262 ]
 [ 1.38991543  0.03664932  0.09959145  0.34653027]
 [-0.92351533 -0.22773217  1.22678825 -0.94808752]
 [-0.0807315   0.97357405  1.19400932  1.46234202]
 [-1.13795449 -1.36273204  0.22980235 -0.69081509]]
<class 'numpy.ndarray'>
DatetimeIndex(['2027-01-01', '2027-01-02', '2027-01-03', '2027-01-04',
               '2027-01-05', '2027-01-06'],
              dtype='datetime64[ns

In [21]:
import numpy as np
import pandas as pd

df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20270102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
# 可以用字典的方式创建DataFrame，一列一个键值对
# 其中键表示列名，值表示列的数据。每一列的数据类型可以不同，例如浮点数、时间戳、整数、分类数据和字符串。
print(df2)
print(df2.dtypes)  # 每列数据形式可以不同
# 上面每一个数据的意思是
# "A": 1.0 表示这一列的所有值都是浮点数1.0
# "B": pd.Timestamp("20270102") 表示这一列的所有值都是时间戳2027-01-02
# "C": pd.Series(1, index=list(range(4)), dtype="float32") 表示这一列是一个长度为4的浮点数序列，值都是1.0
# "D": np.array([3] * 4, dtype="int32") 表示这一列是一个长度为4的整数数组，值都是3
# "E": pd.Categorical(["test", "train", "test", "train"]) 表示这一列是一个分类数据，有两个类别 "test" 和 "train"
# "F": "foo" 表示这一列的所有值都是字符串 "foo"
# 因为E数据最长,所以其他键值对的值被赋值过来了

print(pd.Series(1, index=list(range(4)), dtype="float32"))
# Series打印的时候有索引,实际在加入上面的字典以后,并不打印索引(理解为索引是隐藏属性,print能打印出来纯粹是方便查看)
# 发现pd里面应该就是两种数据,一个是Series,一个是DataFrame
# numpy里的array可以叫矩阵,那pd里的Series和DataFrame叫什么? Series可以理解为一维数组或列表，而DataFrame可以理解为二维表格或矩阵。Series是一种带有索引的一维数据结构，而DataFrame是由多个Series组成的二维数据结构，每个Series代表一列数据。
# 总之pd里的数据,是带有索引标题的(就像表格一样)

     A          B    C  D      E    F
0  1.0 2027-01-02  1.0  3   test  foo
1  1.0 2027-01-02  1.0  3  train  foo
2  1.0 2027-01-02  1.0  3   test  foo
3  1.0 2027-01-02  1.0  3  train  foo
A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object
0    1.0
1    1.0
2    1.0
3    1.0
dtype: float32


In [ ]:
import numpy as np
import pandas as pd

df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20270102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)


df2.describe()  # 这里是jypter好心,给我们打印了
# describe()方法用于生成DataFrame的描述性统计信息，包括计数、均值、标准差、最小值、四分位数和最大值等。
# 25% 50% 75%是四分位数,即将数据按大小顺序分为四等份,25%是第一四分位数,50%是中位数,75%是第三四分位数
# std是标准差,即数据的离散程度,越大表示数据越分散,越小表示数据越集中


,A,B,C,D
count,4.0,4,4.0,4.0
mean,1.0,2027-01-02 00:00:00,1.0,3.0
min,1.0,2027-01-02 00:00:00,1.0,3.0
25%,1.0,2027-01-02 00:00:00,1.0,3.0
50%,1.0,2027-01-02 00:00:00,1.0,3.0
75%,1.0,2027-01-02 00:00:00,1.0,3.0
max,1.0,2027-01-02 00:00:00,1.0,3.0
std,0.0,NaN,0.0,0.0


In [34]:
import pandas as pd
import numpy as np

df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20270102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)


print(df2.T)
# T属性用于获取DataFrame的转置，即行列互换。转置后的
# 有个\表示换行

print(df2.sort_index(axis=1, ascending=False))
# sort_index()方法用于按照指定的轴对DataFrame进行排序。axis=1表示行方向的索引排序，ascending=False表示降序排列。
print(df2.sort_index(axis=0, ascending=False))
print(df2.sort_values(by="E"))


                     0                    1                    2  \
A                  1.0                  1.0                  1.0   
B  2027-01-02 00:00:00  2027-01-02 00:00:00  2027-01-02 00:00:00   
C                  1.0                  1.0                  1.0   
D                    3                    3                    3   
E                 test                train                 test   
F                  foo                  foo                  foo   

                     3  
A                  1.0  
B  2027-01-02 00:00:00  
C                  1.0  
D                    3  
E                train  
F                  foo  
     F      E  D    C          B    A
0  foo   test  3  1.0 2027-01-02  1.0
1  foo  train  3  1.0 2027-01-02  1.0
2  foo   test  3  1.0 2027-01-02  1.0
3  foo  train  3  1.0 2027-01-02  1.0
     A          B    C  D      E    F
3  1.0 2027-01-02  1.0  3  train  foo
2  1.0 2027-01-02  1.0  3   test  foo
1  1.0 2027-01-02  1.0  3  train  foo
0  1.0

In [23]:
# pandas和numpy的区别：
# 1. 数据结构不同：
#    - numpy主要提供ndarray，多维数组。
#    - pandas主要提供Series（一维）和DataFrame（二维）。
# 2. 数据类型不同：
#    - numpy主要处理数值型数据。
#    - pandas可以处理多种数据类型，包括数值型、字符串、时间序列等。
# 3. 数据操作不同：
#    - numpy提供了丰富的数学函数和线性代数操作。
#    - pandas提供了更高级的数据操作功能，如数据清洗、缺失值处理、分组聚合等。
# 4. 索引和标签不同：
#    - numpy使用整数索引。
#    - pandas使用标签索引，可以通过行标签和列标签访问数据。
# 5. 性能和内存使用：
#    - numpy在处理大规模数值计算时性能更高，内存使用更低。
#   - pandas在处理结构化数据时更方便，但可能会占用更多内存。
# 总结：
# - 如果主要处理数值计算和矩阵运算，使用numpy。
# - 如果主要处理结构化数据和数据分析，使用pandas。